import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import React from "react";
import Navbar from "@/components/Navbar";
import Header from "@/components/Header";

const raleway = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <div className="w-full sticky top-0">
          <Navbar />
        </div>
        <div className="w-full h-[80vh]">
          <Header />
        </div>
        <div>{children}</div>
      </body>
    </html>
  );
}
